### ISSUE TITLE
[Bug]:  Files App Crashing

### ISSUE THREAD

**Issue by remdu92** [LeeXDA21/UnboundHub#8]
### What is your Telegram Username?

@cailloux92

### Device

SM-G980F (Galaxy S20 4G)

### Unbound Version

V1.5.0

### Bug Description

Hi lee,

Just upgraded to 1.5 from 1.2

When going into any app and requesting to import a file, com.google.android.documentsui is crashing.
happen two times :

Open Alpha (magisk) app, --> module tab --> clicking on 'install from storage" --> selecting the classic "files" app --> crash
Open Mifare Classic tool --> tools --> import/export/convert --> import dump --> selecting "files" app, crash

So i'm stuck to import a file.
I can use samsung my files as a workaround, BUT, this app is responsible of granting sdcard access for files manager app

### Bug Visual Description

https://youtube.com/shorts/pqR8r9AAroE

### Log File(s)

--------- beginning of crash
10-09 17:11:01.328 17879 17879 E AndroidRuntime: FATAL EXCEPTION: main
10-09 17:11:01.328 17879 17879 E AndroidRuntime: Process: com.google.android.documentsui, PID: 17879
10-09 17:11:01.328 17879 17879 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.google.android.documentsui/com.android.documentsui.picker.PickActivity}: java.lang.SecurityException: Cannot read compat change
10-09 17:11:01.328 17879 17879 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4035)
10-09 17:11:01.328 17879 17879 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4201)
10-09 17:11:01.328 17879 17879 E AndroidRuntime: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
10-09 17:11:01.328 17879 17879 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
10-09 17:11:01.328 17879 17879 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
10-09 17:11:01.328 17879 17879 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2438)
10-09 17:11:01.328 17879 17879 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
10-09 17:11:01.328 17879 17879 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:226)
10-09 17:11:01.328 17879 17879 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:313)
10-09 17:11:01.328 17879 17879 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8669)
10-09 17:11:01.328 17879 17879 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
10-09 17:11:01.328 17879 17879 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
10-09 17:11:01.328 17879 17879 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
10-09 17:11:01.328 17879 17879 E AndroidRuntime: Caused by: java.lang.SecurityException: Cannot read compat change
10-09 17:11:01.328 17879 17879 E AndroidRuntime: 	at android.os.Parcel.createExceptionOrNull(Parcel.java:2438)
10-09 17:11:01.328 17879 17879 E AndroidRuntime: 	at android.os.Parcel.createException(Parcel.java:2422)
10-09 17:11:01.328 17879 17879 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:2405)
10-09 17:11:01.328 17879 17879 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:2347)
10-09 17:11:01.328 17879 17879 E AndroidRuntime: 	at com.android.internal.compat.IPlatformCompat$Stub$Proxy.isChangeEnabledByPackageName(IPlatformCompat.java:927)
10-09 17:11:01.328 17879 17879 E AndroidRuntime: 	at android.app.compat.ChangeIdStateCache.recompute(ChangeIdStateCache.java:71)
10-09 17:11:01.328 17879 17879 E AndroidRuntime: 	at android.app.compat.ChangeIdStateCache.recompute(ChangeIdStateCache.java:31)
10-09 17:11:01.328 17879 17879 E AndroidRuntime: 	at android.app.PropertyInvalidatedCache.query(PropertyInvalidatedCache.java:562)
10-09 17:11:01.328 17879 17879 E AndroidRuntime: 	at android.app.compat.CompatChanges.isChangeEnabled(CompatChanges.java:77)
10-09 17:11:01.328 17879 17879 E AndroidRuntime: 	at com.android.documentsui.base.Shared.shouldRestrictStorageAccessFramework(Shared.java:179)
10-09 17:11:01.328 17879 17879 E AndroidRuntime: 	at com.android.documentsui.BaseActivity.getState(BaseActivity.java:403)
10-09 17:11:01.328 17879 17879 E AndroidRuntime: 	at com.android.documentsui.BaseActivity.onCreate(BaseActivity.java:153)
10-09 17:11:01.328 17879 17879 E AndroidRuntime: 	at com.android.documentsui.picker.PickActivity.onCreate(PickActivity.java:104)
10-09 17:11:01.328 17879 17879 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:8290)
10-09 17:11:01.328 17879 17879 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:8270)
10-09 17:11:01.328 17879 17879 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)
10-09 17:11:01.328 17879 17879 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4009)
10-09 17:11:01.328 17879 17879 E AndroidRuntime: 	... 12 more
10-09 17:11:01.373  6949 10492 E WindowManager: win=Window{ddb4ee5 u0 Splash Screen com.google.android.documentsui EXITING} destroySurfaces: appStopped=false win.mWindowRemovalAllowed=true win.mRemoveOnExit=true win.mViewVisibility=0 caller=com.android.server.wm.ActivityRecord.destroySurfaces:24 com.android.server.wm.ActivityRecord.destroySurfaces:1 com.android.server.wm.WindowState.onExitAnimationDone:217 com.android.server.wm.ActivityRecord$$ExternalSyntheticLambda13.accept:2 java.util.ArrayList.forEach:1262 com.android.server.wm.ActivityRecord.onAnimationFinished:143 com.android.server.wm.ActivityRecord.postApplyAnimation:11 
10-09 17:11:01.379  6949 10492 E WindowManager: win=Window{89b5ecd u0 io.github.vvb2060.magisk/com.topjohnwu.magisk.ui.MainActivity} destroySurfaces: appStopped=false win.mWindowRemovalAllowed=false win.mRemoveOnExit=false win.mViewVisibility=8 caller=com.android.server.wm.ActivityRecord.destroySurfaces:24 com.android.server.wm.ActivityRecord.notifyAppResumed:70 com.android.server.wm.Task.resumeTopActivityInnerLocked:1215 com.android.server.wm.Task.resumeTopActivityInnerLocked:23 com.android.server.wm.Task.resumeTopActivityUncheckedLocked:43 com.android.server.wm.Task.resumeTopActivityUncheckedLocked:1 com.android.server.wm.ActivityRecord.makeActiveIfNeeded:37 
10-09 17:11:01.449  6949  6982 E Native_CFMS: nativePerfMgrRemoveTask    Fail    tid : 17765    return : -1

### Additional checks

- [X] I have checked other bug reports and this is not a duplicate.
- [X] This is a bug in Project Unbound and NOT any other ROM.
- [X] You understand and declare that if any information provided here is incorrect or instructions have not been followed correctly that it can lead to you being permanently banned from all Unbound owned servers.

**Comment by remdu92** [comment]
Reinstalled the rom + magisk
Issue solved
